backend:
  name: git-gateway
  branch: main

media_folder: "public/images/posts"
public_folder: "/images/posts"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "yml"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", optional: true}
      - {label: "Body", name: "body", widget: "markdown"}
